//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiwi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attraction
    {
        public int AttractionId { get; set; }
        public string AttractionName { get; set; }
        public string AttractionImage { get; set; }
        public string AttractionDescription { get; set; }
        public string AttractionLocation { get; set; }
        public string Address { get; set; }
        public string AttractionLink { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
