//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiwi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Community
    {
        public int CommunityId { get; set; }
        public string CommunityName { get; set; }
        public string CommunityTypeLocation { get; set; }
        public string CommunityTypeDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
