//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiwi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducatiionalInstitution
    {
        public int InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public string InstituionImages { get; set; }
        public int InstituionImageId { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual EducationalInstitutionImage EducationalInstitutionImage { get; set; }
    }
}
