//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiwi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public int JobTypeId { get; set; }
        public int PayTypeId { get; set; }
        public string JobTitile { get; set; }
        public string JobDescription { get; set; }
        public string JobLocation { get; set; }
        public Nullable<System.DateTime> JobPostDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Company { get; set; }
        public string SiteLink { get; set; }
    }
}
